// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// RememberCipherCard defines model for RememberCipherCard.
type RememberCipherCard struct {
	Brand           string `json:"brand"`
	CardHolderName  string `json:"cardHolderName"`
	Code            string `json:"code"`
	ExpirationMonth string `json:"expirationMonth"`
	ExpirationYear  string `json:"expirationYear"`
	Number          string `json:"number"`
}

// RememberCipherCustom defines model for RememberCipherCustom.
type RememberCipherCustom struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// RememberCipherCustomBinary defines model for RememberCipherCustomBinary.
type RememberCipherCustomBinary struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// RememberCipherLogin defines model for RememberCipherLogin.
type RememberCipherLogin struct {
	Login    string `json:"login"`
	Password string `json:"password"`
	Uri      string `json:"uri"`
}

// RememberCipherCardJSONRequestBody defines body for RememberCipherCard for application/json ContentType.
type RememberCipherCardJSONRequestBody = RememberCipherCard

// RememberCipherCustomBinaryJSONRequestBody defines body for RememberCipherCustomBinary for application/json ContentType.
type RememberCipherCustomBinaryJSONRequestBody = RememberCipherCustomBinary

// RememberCipherCustomJSONRequestBody defines body for RememberCipherCustom for application/json ContentType.
type RememberCipherCustomJSONRequestBody = RememberCipherCustom

// RememberCipherLoginJSONRequestBody defines body for RememberCipherLogin for application/json ContentType.
type RememberCipherLoginJSONRequestBody = RememberCipherLogin

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RememberCipherCardWithBody request with any body
	RememberCipherCardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RememberCipherCard(ctx context.Context, body RememberCipherCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RememberCipherCustomBinaryWithBody request with any body
	RememberCipherCustomBinaryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RememberCipherCustomBinary(ctx context.Context, body RememberCipherCustomBinaryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RememberCipherCustomWithBody request with any body
	RememberCipherCustomWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RememberCipherCustom(ctx context.Context, body RememberCipherCustomJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RememberCipherLoginWithBody request with any body
	RememberCipherLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RememberCipherLogin(ctx context.Context, body RememberCipherLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RememberCipherCardWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCardRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherCard(ctx context.Context, body RememberCipherCardJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCardRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherCustomBinaryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCustomBinaryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherCustomBinary(ctx context.Context, body RememberCipherCustomBinaryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCustomBinaryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherCustomWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCustomRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherCustom(ctx context.Context, body RememberCipherCustomJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherCustomRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RememberCipherLogin(ctx context.Context, body RememberCipherLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRememberCipherLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRememberCipherCardRequest calls the generic RememberCipherCard builder with application/json body
func NewRememberCipherCardRequest(server string, body RememberCipherCardJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRememberCipherCardRequestWithBody(server, "application/json", bodyReader)
}

// NewRememberCipherCardRequestWithBody generates requests for RememberCipherCard with any type of body
func NewRememberCipherCardRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cipher-card/remember")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRememberCipherCustomBinaryRequest calls the generic RememberCipherCustomBinary builder with application/json body
func NewRememberCipherCustomBinaryRequest(server string, body RememberCipherCustomBinaryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRememberCipherCustomBinaryRequestWithBody(server, "application/json", bodyReader)
}

// NewRememberCipherCustomBinaryRequestWithBody generates requests for RememberCipherCustomBinary with any type of body
func NewRememberCipherCustomBinaryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cipher-custom-binary/remember")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRememberCipherCustomRequest calls the generic RememberCipherCustom builder with application/json body
func NewRememberCipherCustomRequest(server string, body RememberCipherCustomJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRememberCipherCustomRequestWithBody(server, "application/json", bodyReader)
}

// NewRememberCipherCustomRequestWithBody generates requests for RememberCipherCustom with any type of body
func NewRememberCipherCustomRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cipher-custom/remember")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRememberCipherLoginRequest calls the generic RememberCipherLogin builder with application/json body
func NewRememberCipherLoginRequest(server string, body RememberCipherLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRememberCipherLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewRememberCipherLoginRequestWithBody generates requests for RememberCipherLogin with any type of body
func NewRememberCipherLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cipher-login/remember")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RememberCipherCardWithBodyWithResponse request with any body
	RememberCipherCardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCardResponse, error)

	RememberCipherCardWithResponse(ctx context.Context, body RememberCipherCardJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCardResponse, error)

	// RememberCipherCustomBinaryWithBodyWithResponse request with any body
	RememberCipherCustomBinaryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCustomBinaryResponse, error)

	RememberCipherCustomBinaryWithResponse(ctx context.Context, body RememberCipherCustomBinaryJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCustomBinaryResponse, error)

	// RememberCipherCustomWithBodyWithResponse request with any body
	RememberCipherCustomWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCustomResponse, error)

	RememberCipherCustomWithResponse(ctx context.Context, body RememberCipherCustomJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCustomResponse, error)

	// RememberCipherLoginWithBodyWithResponse request with any body
	RememberCipherLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherLoginResponse, error)

	RememberCipherLoginWithResponse(ctx context.Context, body RememberCipherLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherLoginResponse, error)
}

type RememberCipherCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r RememberCipherCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RememberCipherCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RememberCipherCustomBinaryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r RememberCipherCustomBinaryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RememberCipherCustomBinaryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RememberCipherCustomResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r RememberCipherCustomResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RememberCipherCustomResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RememberCipherLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r RememberCipherLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RememberCipherLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RememberCipherCardWithBodyWithResponse request with arbitrary body returning *RememberCipherCardResponse
func (c *ClientWithResponses) RememberCipherCardWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCardResponse, error) {
	rsp, err := c.RememberCipherCardWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCardResponse(rsp)
}

func (c *ClientWithResponses) RememberCipherCardWithResponse(ctx context.Context, body RememberCipherCardJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCardResponse, error) {
	rsp, err := c.RememberCipherCard(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCardResponse(rsp)
}

// RememberCipherCustomBinaryWithBodyWithResponse request with arbitrary body returning *RememberCipherCustomBinaryResponse
func (c *ClientWithResponses) RememberCipherCustomBinaryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCustomBinaryResponse, error) {
	rsp, err := c.RememberCipherCustomBinaryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCustomBinaryResponse(rsp)
}

func (c *ClientWithResponses) RememberCipherCustomBinaryWithResponse(ctx context.Context, body RememberCipherCustomBinaryJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCustomBinaryResponse, error) {
	rsp, err := c.RememberCipherCustomBinary(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCustomBinaryResponse(rsp)
}

// RememberCipherCustomWithBodyWithResponse request with arbitrary body returning *RememberCipherCustomResponse
func (c *ClientWithResponses) RememberCipherCustomWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherCustomResponse, error) {
	rsp, err := c.RememberCipherCustomWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCustomResponse(rsp)
}

func (c *ClientWithResponses) RememberCipherCustomWithResponse(ctx context.Context, body RememberCipherCustomJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherCustomResponse, error) {
	rsp, err := c.RememberCipherCustom(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherCustomResponse(rsp)
}

// RememberCipherLoginWithBodyWithResponse request with arbitrary body returning *RememberCipherLoginResponse
func (c *ClientWithResponses) RememberCipherLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RememberCipherLoginResponse, error) {
	rsp, err := c.RememberCipherLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherLoginResponse(rsp)
}

func (c *ClientWithResponses) RememberCipherLoginWithResponse(ctx context.Context, body RememberCipherLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*RememberCipherLoginResponse, error) {
	rsp, err := c.RememberCipherLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRememberCipherLoginResponse(rsp)
}

// ParseRememberCipherCardResponse parses an HTTP response from a RememberCipherCardWithResponse call
func ParseRememberCipherCardResponse(rsp *http.Response) (*RememberCipherCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RememberCipherCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRememberCipherCustomBinaryResponse parses an HTTP response from a RememberCipherCustomBinaryWithResponse call
func ParseRememberCipherCustomBinaryResponse(rsp *http.Response) (*RememberCipherCustomBinaryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RememberCipherCustomBinaryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRememberCipherCustomResponse parses an HTTP response from a RememberCipherCustomWithResponse call
func ParseRememberCipherCustomResponse(rsp *http.Response) (*RememberCipherCustomResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RememberCipherCustomResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRememberCipherLoginResponse parses an HTTP response from a RememberCipherLoginWithResponse call
func ParseRememberCipherLoginResponse(rsp *http.Response) (*RememberCipherLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RememberCipherLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /cipher-card/remember)
	RememberCipherCard(w http.ResponseWriter, r *http.Request)

	// (POST /cipher-custom-binary/remember)
	RememberCipherCustomBinary(w http.ResponseWriter, r *http.Request)

	// (POST /cipher-custom/remember)
	RememberCipherCustom(w http.ResponseWriter, r *http.Request)

	// (POST /cipher-login/remember)
	RememberCipherLogin(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /cipher-card/remember)
func (_ Unimplemented) RememberCipherCard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /cipher-custom-binary/remember)
func (_ Unimplemented) RememberCipherCustomBinary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /cipher-custom/remember)
func (_ Unimplemented) RememberCipherCustom(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /cipher-login/remember)
func (_ Unimplemented) RememberCipherLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RememberCipherCard operation middleware
func (siw *ServerInterfaceWrapper) RememberCipherCard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RememberCipherCard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RememberCipherCustomBinary operation middleware
func (siw *ServerInterfaceWrapper) RememberCipherCustomBinary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RememberCipherCustomBinary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RememberCipherCustom operation middleware
func (siw *ServerInterfaceWrapper) RememberCipherCustom(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RememberCipherCustom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RememberCipherLogin operation middleware
func (siw *ServerInterfaceWrapper) RememberCipherLogin(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RememberCipherLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cipher-card/remember", wrapper.RememberCipherCard)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cipher-custom-binary/remember", wrapper.RememberCipherCustomBinary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cipher-custom/remember", wrapper.RememberCipherCustom)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/cipher-login/remember", wrapper.RememberCipherLogin)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xW32/UMAz+VyrDY7duwFPf2MRPDR4ACaHpHnKtd83WxsFJxk5T/3fkpLe70Wp3QzDQ",
	"npqLHef7/MX2XUNFnSWDxjsor8FVDXYqLl8xE8vCMllkrzFud+icWqAs/dIilOA8a7OAPgfXhsWEoc+B",
	"8XvQjDWUp8krvwk0y1f+ND/HykugT9hhN0c+1rZBPlZcj4HMWZl6EkaluH5LbY38UXXTSCuqpw14ZTUr",
	"r8l8IOObLT7fUPGkiwkCf3sufoGaD6xuAowBja4fyOyQxuA8deNEXuByksOlagNupyDHV867gjjSRvHy",
	"H0M5oYU2YwztanuEwirnfhBPP7rAejvAFHsjUjo3xirFhFVg7ZefpSQTtCNUjPwypHc5j79eE3fKQwnv",
	"v36BPBWwREpWuInceG+hl8DanFGEqn0rljdkmwtEi5ypEF/YJbLTZKCEw/2D/QOhRxaNshpKeB63hINv",
	"Iqqiiunck7dc8JDimFdyXr6S3fhe39VQTtV2ShI6f0R1fAAVGY8mHlbWtrqKx4tzR2bdpWT1lPEMSnhS",
	"rNtYMfSwYuKiyL9GV7G2PjFcAXaZ4M9q5RVsiuY5YFTRWTIu6fDs4IV8bgfyVBPE8GcqtP6P0Uh9eAJ5",
	"MHhlsfJYZ7jy6fO1HLHS9uax1O6vy2adPog+mxferVP0zBKxRyfYbyr1gBrtpM7jkSX27HurcjJ0+r8v",
	"SrrpTk0ihUyZTObODqoc/q+qbIxFKE9vD8TTWT8TM8v0itbA7TD4XFkU1w05b1SHfSGDTP4nsFbzNpFe",
	"GRPzgSO0VKlWTHL7rP8ZAAD//1PrsSAuCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
